apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
  annotations:
    service.kubernetes.io/topology-mode: auto
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP