apiVersion: v1
kind: Service
metadata:
  name: fastfood-api-service
  labels:
    app: fastfood-api
spec:
  type: NodePort
  selector:
    app: fastfood-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP