apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-api
  labels:
    app: fastfood-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastfood-api
  template:
    metadata:
      labels:
        app: fastfood-api
    spec:
      containers:
        - name: fastfood-api
          image: devops3ng1nn3r/uaifood:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MYSQL_CONN_URL
              value: "jdbc:mysql://mysql-svc.fastfood.svc.cluster.local:3306/fastfood_db?useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=60000&autoReconnect=true"
          envFrom:
            - configMapRef:
                name: fastfood-config
            - secretRef:
                name: fastfood-secrets
          args:
            - "--spring.profiles.active=prod"