apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: fastfood-staging

commonLabels:
  environment: staging

# Configuração de réplicas para ambiente de staging
replicas:
  - name: fastfood-api
    count: 2  # Mantido como no ambiente base para testes realistas