apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: fastfood-production

commonLabels:
  environment: production

# Configuração de réplicas para ambiente de produção
replicas:
  - name: fastfood-api
    count: 3  # Aumentado para maior disponibilidade em produção
  - name: mysql
    count: 1  # Mantido em 1 (caso você não esteja usando RDS)
